### PR TITLE
Remove jodis, use reborndb/reborn-java instead

### PR DESCRIPTION
**Pull request by qiuyesuifeng**

### CODE REVIEW

**Comment by siddontang** [comment]
Cool

**Comment by ngaut** [comment]
Hava you tested it ?

**Comment by qiuyesuifeng** [comment]
yes, only origin jodis test, but i found that sometimes test case maybe fail for zk KeeperErrorCode.
perhaps i should fix it, though i don't like java at all.

**Comment by qiuyesuifeng** [comment]
see https://github.com/reborndb/reborn-java/pull/1

**Pull request merged**
