### PR TITLE
Recommend go version

### PR DESCRIPTION
**Pull request by ngaut**
go1.4 has some performance issue.

### CODE REVIEW

**Comment by xiang90** [comment]
It would be great if you can tell why you suggest 1.3.3 with one simple sentence. 

Or most people would think it is because compatibility reason or reborn relies on some strange behavior of go 1.3.3. 

Thanks.

**Comment by ngaut** [comment]
The gc pause time is unacceptable in user's production environment.
And it work well and faster after switch go version to 1.3.3.

**Comment by ngaut** [comment]
PTAL

**Comment by xiang90** [comment]
LGTM.

Ideally we can show people some benchmark difference. (we are not providing the binary and some people might not install go 1.3. so we need give them some motivation.)

**Comment by ngaut** [comment]
We may reconsider this after go1.5

**Pull request merged**
